# docker build -f Dockerfile.backend -t taxoniumbackend .
FROM node:17.9-alpine
WORKDIR /app

COPY taxonium_backend ./taxonium_backend
COPY taxonium_data_handling ./taxonium_data_handling
WORKDIR /app/taxonium_backend
RUN yarn --frozen-lockfile


EXPOSE 80
CMD node --experimental-fetch --max-old-space-size=3900 server.js --database_dir ./database/ --port 80 --config_json config_public.json
