import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const directory = dirname(fileURLToPath(import.meta.url));
const compiler = process.env.WASM64_CLANG || "clang";
const temporary = await mkdtemp(join(tmpdir(), "taxonium-wasm64-"));
try {
  const output = join(temporary, "tree-processing.wasm");
  execFileSync(
    compiler,
    [
      "--no-default-config",
      "--target=wasm64-unknown-unknown",
      "-O3",
      "-nostdlib",
      "-fno-builtin",
      "-ffp-contract=off",
      "-Wall",
      "-Wextra",
      "-Werror",
      "-Wl,--no-entry",
      "-Wl,--export-memory",
      "-Wl,--strip-all",
      join(directory, "tree-processing.c"),
      "-o",
      output,
    ],
    { stdio: "inherit" },
  );
  const bytes = await readFile(output);
  const hash = createHash("sha256")
    .update(await readFile(join(directory, "tree-processing.c")))
    .digest("hex");
  await writeFile(
    join(directory, "treeProcessingBytes.js"),
    `// Generated by build.mjs; source SHA-256: ${hash}\n` +
      `// Embedded so library consumers and inline workers need no extra asset URL.\n` +
      `export default "${bytes.toString("base64")}";\n`,
  );
  console.log(`Built ${bytes.length} bytes of Memory64 WebAssembly.`);
} finally {
  await rm(temporary, { recursive: true, force: true });
}
