import React from "react";

function AboutOverlay({ enabled, setEnabled }) {
  return (
    <div className={`w-full ${enabled ? "" : "hidden"}`}>
      <div
        onClick={() => setEnabled(false)}
        className="fixed w-full h-full bg-black opacity-80 z-40"
      ></div>
      <div
        onClick={() => setEnabled(false)}
        className="fixed w-full h-full  opacity-100 z-40"
      >
        <div
          className=" relative mx-auto mt-5 p-5 bg-white shadow-md z-100 w-4/5 overflow-y-auto opacity-100 "
          style={{ height: "90vh" }}
        >
          <button
            className="absolute top-5 right-5 text-xl font-bold"
            onClick={() => setEnabled(false)}
          >
            X
          </button>
          <h1 className="font-bold mb-3 text-xl">About Cov2Tree-E</h1>
          This website allows you to explore a phylogenetic tree with more than
          a million SARS-Cov-2 sequences, sequenced by researchers around the
          world and built into a tree by the GISAID Initative. The interface was made by{" "}
          <a className="text-blue-700 underline" href="http://theo.io/">
            Theo Sanderson
          </a>{" "}
          using a custom-developed open-source library called{" "}
          <a
            href="http://github.com/theosanderson/taxodium"
            className="text-blue-700 underline"
          >
            {" "}
            Taxodium
          </a>
          .<h1 className="font-bold mb-3 text-xl mt-6">The sequences</h1>
          <p>
            This tree displays sequences generated by a global community of researchers. The sequences are collated and curated by the GISAID Initiative.
          </p>
          <p>
            This website would be empty but for the hard work of all these
            researchers, and their openness in submitting their work to public
            databases, and we gratefully acknowledge this.
          </p>
          <h1 className="font-bold mb-3 text-xl mt-6">The tree</h1>
          <p>
            The tree shown here is generated by the GISAID Initiative, using [...]
            </p>

            <h1 className="font-bold mb-3 text-xl mt-6">Acknowledgement</h1>
          <p>
          We gratefully acknowledge all data contributors, i.e. the Authors and their Originating laboratories responsible for obtaining the specimens, and their Submitting laboratories for generating the genetic sequence and metadata and sharing via the GISAID Initiative<sup>1</sup> on which this research is based. <br /><br />1. Elbe, S., and Buckland-Merrett, G. (2017) Data, disease and diplomacy: GISAID’s innovative contribution to global health. Global Challenges, 1:33-46. DOI: <a class="underline" href="https://doi.org/10.1002/gch2.1018">10.1002/gch2.1018</a> PMCID: <a class="underline" href="https://pubmed.ncbi.nlm.nih.gov/31565258/">31565258</a>

            </p>
            
          </div>
          
         
        </div>{" "}
      </div>
  
  );
}

export default AboutOverlay;
