apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxonium-proxy-deployment
spec:
  replicas: 1 # Number of replicas
  selector:
    matchLabels:
      app: taxonium-proxy
  template:
    metadata:
      labels:
        app: taxonium-proxy
    spec:
      containers:
        - name: taxonium-proxy
          image: theosanderson/taxonium_proxy:master
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: taxonium-proxy-service
spec:
  selector:
    app: taxonium-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taxonium-proxy-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx" # assuming you are using nginx ingress controller
spec:
  rules:
    - host: proxied.taxonium.org
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: taxonium-proxy-service
                port:
                  number: 80
  tls:
    - hosts:
        - proxied.taxonium.org
      secretName: tls-proxy3
