apiVersion: v2
name: viral-usher-web
description: A Helm chart for Viral Usher Web application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - viral-usher
  - bioinformatics
  - genomics
maintainers:
  - name: Viral Usher Team
home: https://github.com/yourusername/viral_usher_web
sources:
  - https://github.com/yourusername/viral_usher_web
dependencies:
  - name: minio
    version: 5.3.0
    repository: https://charts.min.io/
    condition: minio.enabled
