name: TypeScript check-types

on:
  push:
    paths:
      - 'taxonium_component/**'
      - 'taxonium_data_handling/**'
  pull_request:
    paths:
      - 'taxonium_component/**'
      - 'taxonium_data_handling/**'
  workflow_dispatch:

jobs:
  check-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: NODE_OPTIONS='--max-old-space-size=4096' npm install --force
        working-directory: ./taxonium_component

      - name: Run check-types
        run: npm run check-types
        working-directory: ./taxonium_component
