name: Playwright Tests
on:
  repository_dispatch:
  workflow_dispatch:
  workflow_call:
jobs:
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: tfci-taxonium-config
          path: ./data/
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: NODE_OPTIONS='--max-old-space-size=4096' yarn install
        working-directory: ./taxonium_website
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
        working-directory: ./taxonium_website
      - name: Build
        run: yarn build
        working-directory: ./taxonium_website
      - name: Run Playwright tests
        run: pwd
          yarn playwright test
        working-directory: ./taxonium_website
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: ./taxonium_website/playwright-report/
          retention-days: 30
