name: Playwright Tests
on:
  repository_dispatch:
  workflow_dispatch:
  workflow_call:
jobs:
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: tfci-taxonium-config
          path: ./data/
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: taxonium_website/package-lock.json
      - name: Build taxonium_component
        run: |
          cd ../taxonium_component
          npm --prefix ../taxonium_data_handling install && npm ci --legacy-peer-deps
          NODE_OPTIONS='--max-old-space-size=6144' npm run build
        working-directory: ./taxonium_website
      - name: Install website dependencies
        run: npm ci --legacy-peer-deps
        working-directory: ./taxonium_website
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./taxonium_website
      - name: Build the application
        run: NODE_OPTIONS='--max-old-space-size=6144' npm run build
        working-directory: ./taxonium_website
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ./taxonium_website
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: ./taxonium_website/playwright-report/
          retention-days: 30
