name: React 17 Compatibility Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  react17-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          
      - name: Install dependencies in taxonium_component
        run: |
          cd taxonium_component
          yarn install --frozen-lockfile
          
      - name: Build taxonium_component
        run: |
          cd taxonium_component
          yarn build
          
      - name: Create React 17 test app with create-react-app
        run: |
          npx create-react-app react17-test-app
          cd react17-test-app
          
          # Downgrade to React 17
          yarn add react@17.0.2 react-dom@17.0.2
          
          # Install the locally built taxonium-component
          yarn add file:../taxonium_component
          
          # Create a simple test component
          cat > src/App.js << EOF
          import React from 'react';
          import { Taxonium } from 'taxonium-component';
          import './App.css';
          
          // Simple data for test
          const simpleData = {
            status: "loaded",
            filename: "test.nwk",
            data: "((A:0.1,B:0.2):0.3,(C:0.4,D:0.5):0.6);",
            filetype: "nwk"
          };
          
          function App() {
            return (
              <div className="App">
                <header className="App-header">
                  <h1>Taxonium React 17 Compatibility Test</h1>
                  <p>This component can be imported and used in React 17</p>
                  <div id="taxonium-test-container" style={{ width: '100%', height: '100px', border: '1px solid white' }}>
                    <Taxonium sourceData={simpleData} />
                  </div>
                </header>
              </div>
            );
          }
          
          export default App;
          EOF
          
          # Create a simple test
          cat > src/App.test.js << EOF
          import { render, screen } from '@testing-library/react';
          import App from './App';
          
          test('renders the Taxonium component in React 17', () => {
            // This will throw an error if Taxonium cannot be imported or rendered
            render(<App />);
            
            // Check if the header content renders
            const headerElement = screen.getByText(/Taxonium React 17 Compatibility Test/i);
            expect(headerElement).toBeInTheDocument();
            
            // Check if the test container for Taxonium exists
            const containerElement = document.getElementById('taxonium-test-container');
            expect(containerElement).toBeInTheDocument();
          });
          EOF
          
      - name: Run React 17 compatibility test
        run: |
          cd react17-test-app
          CI=true yarn test --passWithNoTests
          
      - name: Build React 17 app
        if: success()
        run: |
          cd react17-test-app
          yarn build