name: React 17 Compatibility Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  react17-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          
      - name: Install dependencies in taxonium_data_handling
        run: |
          cd taxonium_data_handling
          yarn install --frozen-lockfile
          
      - name: Build taxonium_data_handling
        run: |
          cd taxonium_data_handling
          yarn build
          
      - name: Install dependencies in taxonium_component
        run: |
          cd taxonium_component
          yarn install --frozen-lockfile
          
      - name: Build taxonium_component
        run: |
          cd taxonium_component
          yarn build
          
      - name: Create React 17 test app
        run: |
          mkdir -p react17-test-app
          cd react17-test-app
          
          # Initialize package.json
          cat > package.json << EOF
          {
            "name": "react17-test-app",
            "version": "1.0.0",
            "private": true,
            "dependencies": {
              "react": "^17.0.2",
              "react-dom": "^17.0.2",
              "taxonium-component": "file:../taxonium_component"
            },
            "scripts": {
              "test": "node test.js"
            }
          }
          EOF
          
          # Create test file
          cat > test.js << EOF
          const React = require('react');
          const taxonium = require('taxonium-component');
          
          // Check if Taxonium component can be imported
          if (!taxonium) {
            console.error('Failed to import taxonium-component');
            process.exit(1);
          }
          
          console.log('Successfully imported taxonium-component in a React 17 environment');
          
          // Check if the main component exists
          if (!taxonium.Taxonium) {
            console.error('Taxonium component not found in the package');
            process.exit(1);
          }
          
          console.log('Taxonium component exists in the package');
          
          // Test if we can create a React element from the component
          try {
            const element = React.createElement(taxonium.Taxonium, {});
            if (!element) {
              console.error('Failed to create React element from Taxonium component');
              process.exit(1);
            }
            console.log('Successfully created React element from Taxonium component');
          } catch (error) {
            console.error('Error creating React element:', error);
            process.exit(1);
          }
          
          console.log('React 17 compatibility test passed!');
          process.exit(0);
          EOF
          
          # Install dependencies
          yarn install
          
      - name: Run React 17 compatibility test
        run: |
          cd react17-test-app
          yarn test